function claimKind(record) {
  if (record.evidence?.state === 'proven_optimal') {
    return {
      label: 'Proven optimal',
      description: 'The verified construction reaches the attached rigorous upper bound.'
    };
  }
  return {
    label: 'Verified best known',
    description: 'This is the best independently verified construction in this release; global optimality is not claimed.'
  };
}

export function buildProvenanceJourney(record, release, integrity, source) {
  if (!record || !release || !integrity?.digest || !source) return [];
  const claim = claimKind(record);
  return [
    {
      id: 'identity',
      label: 'Research identity',
      value: record.experimentId,
      description: `Record ${record.id} fixes the triangle family, container, and experiment parameters.`
    },
    {
      id: 'construction',
      label: 'Construction origin',
      value: record.provenance.generator,
      description: `Generated by ${record.provenance.generator} from seed ${record.provenance.seed}; attributed to ${record.provenance.contributor}.`
    },
    {
      id: 'verification',
      label: 'Independent verification',
      value: record.verification.verifier,
      description: `${record.verification.certificate}; stability: ${record.verification.stability?.classification ?? 'unavailable'}; fingerprint: ${record.verification.fingerprint}.`
    },
    {
      id: 'claim',
      label: claim.label,
      value: `${record.bounds.lowerBound} ≤ optimum ≤ ${record.bounds.upperBound}`,
      description: claim.description
    },
    {
      id: 'release',
      label: 'Release integrity',
      value: `${integrity.algorithm}: ${integrity.digest}`,
      description: `Release ${release.version} from ${release.releasedAt}; ${integrity.artifact} verified as ${integrity.scope} via ${source}.`
    }
  ];
}
